django_tuto/urls.py
from django.conf.urls import patterns, include, url
from polls import urls
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    # url(r'^django_tuto/', include('django_tuto.foo.urls')),
    url(r'^polls/', include(urls, namespace='polls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('polls.views',
    url(r'^$', 'index', name='index'),
    url(r'(?P<poll_id>\d+)/$', 'detail', name='detail'),
    url(r'(?P<poll_id>\d+)/edit/$', 'edit', name='edit'),
)

polls/models.py
from django.db import models
from django.utils import timezone
from django.db.models import Sum
import datetime


class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Publication Date',
                                    default=timezone.now)

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        """
        Returns True or False depending on whether the poll
        was published in the last 24hs.
        """
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.boolean = True
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.short_description = 'Was published recently?'

    @property
    def total_votes_count(self):
        """
        Returns the count of all votes associated to this poll
        """
        return self.choice_set.all().aggregate(Sum('votes'))[ 'votes__sum'] or 0


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    class Meta:
        order_with_respect_to = 'poll'

    @property
    def votes_percentage(self):
        """
        Returns the percentage of votes this choice has, from the related poll
        """
        try:
            return (self.votes * 100) / self.poll.total_votes_count
        except ZeroDivisionError:
            return 0

    def __unicode__(self):
        return '{0} ({1})'.format(self.choice, self.votes)

polls/forms.py
from django import forms
from polls.models import Poll, Choice
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.forms.widgets import HiddenInput


class VoteForm(forms.Form):
    choice = forms.ModelChoiceField(
        queryset=Choice.objects.all(),
        widget=forms.RadioSelect,
        empty_label=None

    )

    def __init__(self, *args, **kwargs):
        poll = kwargs.pop('poll')
        super(VoteForm, self).__init__(*args, **kwargs)
        self.fields['choice'].queryset = poll.choice_set.all()


class PollEditForm(forms.ModelForm):
    class Meta:
        model = Poll
        fields = ('question',)


class ChoiceEditForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ('choice',)


class ChoiceEditInlineFormset(BaseInlineFormSet):
    def get_queryset(self):
        """
        Redefine the queryset to retrieve all the poll's choices in order
        """
        self._queryset = self.instance.choice_set.order_by('_order')
        return self._queryset

    def add_fields(self, form, index):
        super(ChoiceEditInlineFormset, self).add_fields(form, index)

        # The order field must be rendered as a hidden input
        form.fields['ORDER'].widget = HiddenInput(attrs={'class': 'order'})

    def save(self, commit=True):
        """
        Update the choice's order on save
        """
        super(ChoiceEditInlineFormset, self).save(commit)

        order = []
        for form in self.ordered_forms:
            order.append(form.cleaned_data['id'].pk)

        self.instance.set_choice_order(order)


ChoiceInlineFormSet = inlineformset_factory(Poll, Choice, form=ChoiceEditForm,
                                            formset=ChoiceEditInlineFormset,
                                            can_order=True)

polls/views.py
from polls.models import Poll
from polls.forms import VoteForm, ChoiceInlineFormSet, PollEditForm
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView
from django.contrib import messages
from django.views.generic.edit import FormView


index = ListView.as_view(
    queryset=Poll.objects.all()[:5],
    context_object_name='polls_list',
    template_name='polls/index.html')


class DetailView(FormView):
    """
    Serve and process votes for each poll
    """
    form_class = VoteForm
    http_method_names = ['get', 'post']
    template_name = 'polls/detail.html'

    def dispatch(self, request, *args, **kwargs):
        """
        Get the appropiate poll instance
        """
        self.poll = get_object_or_404(Poll, pk=kwargs.get('poll_id'))
        return super(DetailView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        """
        Add the poll object to the kwargs as needed to instatiate VoteForm
        """
        kwargs = super(DetailView, self).get_form_kwargs()
        kwargs.update({'poll': self.poll})
        return kwargs

    def get_context_data(self, **kwargs):
        """
        Add the current poll object to the context
        """
        kwargs.update({'poll': self.poll})
        return kwargs

    def form_valid(self, form):
        choice = form.cleaned_data['choice']
        choice.votes += 1
        choice.save()
        messages.add_message(self.request, messages.INFO,
                             'Your choice has been saved')
        return redirect('polls:detail', poll_id=self.poll.id)


detail = DetailView.as_view()


def edit(request, poll_id):
    """
    Lets the user edit the poll question and the choices & their display order
    """
    poll = get_object_or_404(Poll, pk=poll_id)
    form = PollEditForm(instance=poll)
    formset = ChoiceInlineFormSet(instance=poll)

    if request.method == "POST":
        form = PollEditForm(request.POST, instance=poll)
        formset = ChoiceInlineFormSet(request.POST, request.FILES,
                                      instance=poll)
        if form.is_valid() and formset.is_valid():
            form.save()
            formset.save()
            return redirect('polls:detail', poll_id=poll.pk)

    return render(request, 'polls/edit.html', {'poll': poll, 'form': form,
                                               'formset': formset})

polls/templates/polls/detail.html
{% extends 'main.html' %}
{% load url from future %}
{% load poll_tags %}

{% block title %}{{ poll.question }}{% endblock %}
{% block h1_title %}{{ poll.question }}{% endblock %}
{% block inner_content %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    <form action="{% url 'polls:detail' poll_id=poll.id %}" method="POST">
        {% csrf_token %}
        {% for field in form.choice %}
            <label class="radio">
                <input type="radio" name="{{ field.name }}" id="" value="{{ field.choice_value }}" >
                {{ field.choice_label }}
            </label> 
            {% votes_percentage_bar field.choice_value %}
        {% endfor %}
        <input class="btn btn-primary" type="submit" value="Vote" />
        <a class="btn" href="{% url 'polls:edit' poll.pk %}">Edit</a>
    </form>
    <hr />
    <a href="{% url 'polls:index' %}" class='link'>&lt;&lt; Back to polls list</a>
    |
    <a href="{% url 'home' %}" class='link'>Home</a>
{% endblock inner_content %}

polls/templates/polls/edit.html
{% extends 'main.html' %}
{% load url from future %}
{% load staticfiles %}

{% block title %}{{ poll.question }}{% endblock %}
{% block h1_title %}Editing: {{ poll.question }}{% endblock %}
{% block inner_content %}
    {% for message in messages %}
    {{ message }}
    {% endfor %}
    {% for error in form.question.errors %}
        <div class="alert alert-danger">{{ error }}</div>
    {% endfor %}
    {% for error in formset.non_field_errors %}
        {{ error }}
    {% endfor %}

    <form action="{% url 'polls:edit' poll_id=poll.pk %}" method="POST">
        {% csrf_token %}
        <div class="form-inline">
            <label for="{{ form.question.id }}">{{ form.question.label }}</label>
            {{ form.question }}
        </div>
        <br/>
        <div id="sortable" class="form-horizontal">
            {{ formset.management_form }}
            {% for f in formset %}
                <div class="control-group {% if f.errors %} alert {% endif %}">
                    {% if f.errors %}
                    <div class="alert alert-danger">
                        {% for error in f.choice.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                    {% endif %}
                    <label class="control-label">{{ f.choice.label }} {{ forloop.counter }}</label>
                    <div class="controls"> {{ f.choice }} </label>
                    {{ f.id }}
                    <label class="checkbox inline">
                        {{ f.DELETE.label }}
                        {{ f.DELETE }}
                    </label>
                    {{ f.ORDER }}
                    </div>
                </div>
            {% endfor %}
        </div>
        <br/>
        <input class="btn" type="submit" value="Save" />
    </form>

    <hr />
    <a href="{% url 'polls:index' %}" class='link'>&lt;&lt; Back to polls list</a>
    <a href="{% url 'home' %}" class='link'>Home</a>
{% endblock inner_content %}

{% block body_extra %}
<script src="{% static "js/jquery-ui-1.10.1.custom.min.js" %}"></script>
<script>
    $(function(){
        var $sortable = $('#sortable');
        $sortable.sortable({
            axis: 'y',
            update: function(e, ui) {
                $sortable.find('.order').each(function(i, e){
                    var $elem = $(e);
                    // Check that the order field has a value before
                    // updating it.
                    if($elem.val() !== '') { $elem.val(i); }
                });
            }
        });
    });
</script>
{% endblock body_extra %}

polls/templates/polls/index.html
{% extends 'main.html' %}
{% load url from future %}

{% block title %}Polls list{% endblock %}
{% block h1_title %}Polls list{% endblock h1_title %}
{% block inner_content %}
    {% if polls_list %}  
        <ul>
        {% for poll in polls_list %}
        <li><a href="{% url 'polls:detail' poll_id=poll.id %}">{{ poll.question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>Sorry, no polls found.</p>
    {% endif %}

    <hr />
    <a href="{% url 'home' %}" class='link'>&lt;&lt; Back to home</a>
{% endblock inner_content %}

polls/templates/polls/poll_vote_percentage_bar.html
<div class="progress">
    <div class="bar" style="width: {{ choice.votes_percentage }}%;"></div>
</div>

templates/base.html
{% load url from future %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>{% block title %}{% endblock title %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- CSS -->
        <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
        <style type="text/css">

          /* Custom page CSS
          -------------------------------------------------- */
          /* Not required for template or sticky footer method. */

          .container {
            width: auto;
            max-width: 680px;
          }

        </style>
        <link href="{% static "css/bootstrap-responsive.css" %}" rel="stylesheet">

        <!-- Fav and touch icons -->
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
        <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/ico/favicon.png">
        {% block head_extra %}{% endblock head_extra %}
    </head>

    <body>
        {% block main_content %}{% endblock main_content %}

        <!-- Le javascript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static "js/jquery-1.9.1.js" %}"></script>
        {% block body_extra %}{% endblock body_extra %}
    </body>
</html>

templates/home.html
{% extends "main.html" %}
{% load url from future %}
{% block title %}Welcome!{% endblock title %}
{% block h1_title %}Welcome to our polls site!{% endblock h1_title %}
{% block p_lead %}<a href="{% url 'polls:index' %}">Participate and win!</a>{% endblock p_lead %}

templates/main.html
{% extends "base.html" %}
{% block main_content %}
<div id="wrap">

  <!-- Begin page content -->
  <div class="container">
    <div class="page-header">
        <h1>{% block h1_title %}{% endblock h1_title %}</h1>
    </div>
    <p class="lead">{% block p_lead %}{% endblock p_lead %}</p>
    {% block inner_content %}{% endblock inner_content %}
  </div>
</div>
{% endblock main_content %}